### ISSUE TITLE
Theme Design

### ISSUE THREAD

**Issue by mbb3-mitch** [noblefr/dataasp#2]
Design a theme with a look and feel that is inviting and is in sync with the ecological aspect or application.

**Comment by mbb3-mitch** [comment]
Natacha, maybe we could use this colour tool.  It converts colours into all the different formats and shows related colours.

http://www.color-hex.com/color/ffffff

**Comment by mbb3-mitch** [comment]
This is a really cool button you can use for designing the buttons.

http://cssgradientbutton.com/

**Comment by natachalevesque** [comment]
Hey we could use this website to help us colour scheme
http://colorschemedesigner.com/csd-3.5/
